// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PeopleApi.Data;

namespace PeopleApi.Migrations
{
    [DbContext(typeof(PessoaContexto))]
    partial class PessoaContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PeopleApi.Models.FaixaEtaria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Faixa1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Faixa10")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Faixa11")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Faixa12")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Faixa13")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Faixa2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Faixa3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Faixa4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Faixa5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Faixa6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Faixa7")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Faixa8")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Faixa9")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FaixasEtarias");
                });

            modelBuilder.Entity("PeopleApi.Models.Pessoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<int>("FaixaEtariaId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FaixaEtariaId");

                    b.ToTable("Pessoas");
                });

            modelBuilder.Entity("PeopleApi.Models.Pessoa", b =>
                {
                    b.HasOne("PeopleApi.Models.FaixaEtaria", "FaixaEtaria")
                        .WithMany("Pessoas")
                        .HasForeignKey("FaixaEtariaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
